### PR TITLE
Reorganize structure for extensions

### PR DESCRIPTION
**Pull request by piotrplenik**
Follow up from #33

### CODE REVIEW

**Comment by kasparsd** [comment]
This looks great @jupeter! Could you please add yourself to the "Credits" section in the `readme` file:

```
- Contributors: [Your Name or Username](http://example.com)
```

**Comment by piotrplenik** [comment]
Of course. Thanks

**Comment by piotrplenik** [comment]
Added

**Comment by kasparsd** [comment]
Thank you @jupeter! This is now merged.

**Pull request merged**
