### PR TITLE
Update build.sh with only sudo if not root

### PR DESCRIPTION
**Pull request by skelgaard**
Created a few mods, that made it only use sudo if not root user

### CODE REVIEW

**Comment by kasparsd** [comment]
Thanks for the pull request @skelgaard! I really appreciate your contribution!

I think you don't have `sudo` installed, right? I'm able to run the build script without any issues from `root` on my box.

**Comment by skelgaard** [comment]
@kasparsd i do have sudo installed, but it failed and said you will be reported if i didn't do that patch on the script... this was on debian 8.2

**Comment by kasparsd** [comment]
@skelgaard I think you might need to add the `root` user to the `sudo` group. See https://wiki.debian.org/sudo

**Comment by skelgaard** [comment]
Yes but default setup is that its not added, and therefor testing if you are root before doing a sudo command is the correct way to go instead of asking users to add root as sudo user as this is really not needed

**Pull request closed without merging**
