### PR TITLE
Add scrpits to install Imagick

### PR DESCRIPTION
**Pull request by piotrplenik**
Locally works like a charm. 
I hope, will helps :)

### CODE REVIEW

**Comment by SergeAx** [comment]
"work like a harm" — what a freudian typo :)

**Comment by piotrplenik** [comment]
Yeah ... :+1:

**Comment by stathis** [comment]
IMHO it would be a good idea to create more scripts like this for other optional/uncommon extensions!

**Comment by piotrplenik** [comment]
I think so.
@kasparsd I can rewrite current exist extensions - if you agree with that idea?

**Comment by kasparsd** [comment]
@stathis That is a good idea. Please open a pull request.

**Comment by kasparsd** [comment]
@jupeter Maybe we should add them in a subdirectory such as `extensions` and have all the individual build scripts there?

**Comment by piotrplenik** [comment]
@kasparsd Yes, very good proposal :+1:

**Comment by stathis** [comment]
@kasparsd Yes, an `extensions` folder sounds good :+1:

**Pull request merged**
