### PR TITLE
Better to do sudo on the when calling the file

### PR DESCRIPTION
**Pull request by ahansson89**

### CODE REVIEW

**Comment by kasparsd** [comment]
I would like avoid using sudo for the whole file.

**Comment by ahansson89** [comment]
The reason that I would like it left out is that I am using it in a Dockerfile and sudo does not work with Docker

**Comment by kasparsd** [comment]
For example, running the whole script with `sudo` will make all the PHP source files from `git checkout` readable only by root.

**Comment by kasparsd** [comment]
@ahansson89 Would this fix the problem http://askubuntu.com/a/477554/115808 or is it something else?

**Comment by ahansson89** [comment]
That is something different

**Pull request closed without merging**
